// "use client";

import Navbar from "@/components/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";
import getCurrentUser from "./actions/getCurrentUser";
import Script from "next/script";
import ToastProvider from "@/components/ToastProvider";
// import { SessionProvider } from "next-auth/react";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const currentUser = await getCurrentUser();

  return (
    <html lang="en">
      <body className={inter.className}>
        {/* useSession 사용 위함 */}
        {/* <SessionProvider> */}
        <Navbar currentUser={currentUser} />
        <ToastProvider />
        {children}
        {/* </SessionProvider> */}
        <Script
          type="text/javascript"
          src="//dapi.kakao.com/v2/maps/sdk.js?appkey=6404a55c112d43f1ed9eb2381db0ac3c&libraries=services,clusterer&autoload=false"
        />
      </body>
    </html>
  );
}
